### PR TITLE
Support for Soapaction

### PR DESCRIPTION
**Pull request by ideaconnect**
In response to issue #8

### CODE REVIEW

**Comment by ideaconnect** [comment]
@conradkdotcom @staabm fancy a review?

**Comment by conradkdotcom** [comment]
@ideaconnect Thanks for your work on this ! I will have a look at this ASAP

**Comment by ideaconnect** [comment]
There was a minor bug which I have fixed 20 minutes ago (hopefully before your tests).

I tested with 
```php
$client = new IDCT\Networking\Soap\Client('http://www.dneonline.com/calculator.asmx?WSDL', [ 'soap_version' => SOAP_1_2 ]);
$data = $client->Multiply(['intA' => 5, 'intB' => 11]);
```

with both SOAP_1_2 and SOAP_1_1. Soap action seems to be properly set now.

**Comment by conradkdotcom** [comment]
@ideaconnect Thanks ! I will try this out with the code at my company the coming week and get back to you then :smiley: 

I have had a lot of other stuff on the plate these last few days, sorry about the delay :wink: 

And thanks for taking the time out of your day to make Soap easier for everyone ! :+1: :heart:

**Comment by conradkdotcom** [comment]
@ideaconnect Sorry for the delay again, have been busy with lots of unexpected stuff. I will check soon. If you are confident about your changes, I'd merge them though, so others can benefit.

**Comment by ideaconnect** [comment]
@conradkdotcom will merge now, let me knof if you encouter any issues in the future so i will fix them ASAP. Thanks for your contribution so far!

**Pull request merged**
